SELECT instance_name FROM v$instance;

-- Create the employees table
CREATE TABLE employees (
    employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(50) ,
    salary NUMBER(8, 2),
    PRIMARY KEY (employee_id)
);

DESCRIBE employees;

-- Insert a row into the employees table
INSERT INTO employees (FIRST_NAME, SALARY) VALUES('darker', 60000);

-- Update the salary of the employee with employee_id 1
UPDATE employees
SET salary = 65000
WHERE employee_id = 1;

SELECT * FROM employees;
